### PR TITLE
sort words in true dictionary order

### PR DESCRIPTION
**Pull request by bilo1967**
Added code to implement dictionary sort

### CODE REVIEW

**Comment by gturri** [comment]
Thanks for the pull request.

I have a few questions:
* what does this new feature do?  To help me understand, can you give an example where the order with `strcoll` isn't the same as the one returned by `strcasecmp`?
* According to the comments on http://php.net/manual/en/function.strcoll.php, `strcoll` is quite sensitive to the locale. I'm not sure I understand why we're using `sk_SK` here. For instance, how would it behaves with text in chinese or russian.

(regarding github: a pull request is related to a branch, so if you want to have all your commits in a single pull request, you should put them on the same branch. In practice it means that you should have submitted a PR based on your branch `bilo1967-patch-1` rather than one based on `patch-2` and one based on `patch-3`. Anyway, since the 2 PRs are already created and since they are quite simple, don't bother with it: I'll be able to cherry-pick)

**Comment by bilo1967** [comment]
Here is what I mean:

```
<pre>
<?php
   $array=array('Übergabe', 'ostfriesland', 'Äpfel', 'Unterführung', 'apfel', 'Österreich', 'pippo');
   $oldLocale=setlocale(LC_ALL, 0);
   setlocale(LC_COLLATE, 'sk_SK.utf8');
   usort($array, 'strcoll');
   setlocale(LC_COLLATE, $oldLocale);
   
   echo "Sorting with strcoll:\n";
   print_r($array);
   
   echo "Sorting with strcasecmp:\n";
   usort($array, 'strcasecmp');
   print_r($array);
?>
</pre>
```

I choose the sk_SK locale because it has all the accents used in EU languages (I guess it would be much better to specify the locale along with the option).

**Comment by bilo1967** [comment]
Fine. I didn't try to do it because I'm completely new to docuwiki internals, but if there's some example code to follow I'll certainly try to do it.

Also, I would like to combine locale order with natural order. I'll try. It shouldn't be that difficult.

**Comment by gturri** [comment]
As a code example, here is how it's done for the `textNS` option: https://github.com/gturri/nspages/blob/master/optionParser.php#L80

**Comment by gturri** [comment]
Supersded by #94

**Pull request closed without merging**
