### PR TITLE
Fix PHP warning and code cleanup

### LINKED ISSUE #143: Uninitialized string offset in optionParser.php on line 126
The following tag  is throwing a warning:

> Warning: Uninitialized string offset -1 in .../dokuwiki/nspages/optionParser.php on line 126

```
<nspages -r -title -sortByDate -reverse -numberedList -nbItemsMax=10 -textPages="" -exclude:wiki: -exclude:[start wiki: syntax ]>
```

PHP 8.2, DokuWiki Jack Jackrum, nspages 2023-02-28

Backtrace

```
#0 .../lib/plugins/nspages/optionParser.php(126): dokuwiki\ErrorHandler::errorHandler(2, 'Uninitialized s...', '.../w...', 126)
#1 .../lib/plugins/nspages/optionParser.php(93): optionParser::_addListOfItemsToExclude(Array, Array, Array)
#2 .../lib/plugins/nspages/syntax.php(88): optionParser::checkExclude(' -exclud...', Array, Array, false)
#3 .../inc/parser/handler.php(284): syntax_plugin_nspages->handle(' -exclud...', 5, 530, Object(Doku_Handler))
#4 .../inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin('<nspages -r -ti...', 5, 530, 'nspages')
#5 .../inc/Parsing/Lexer/Lexer.php(197): dokuwiki\Parsing\Lexer\Lexer->invokeHandler('<nspages -r -ti...', 5, 530)
#6 .../inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens('', '<nspages -r -ti...', '_plugin_nspages', 530, 530)
#7 .../inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse('\n\n\n===== Cr\xC3\xA9at...')
#8 .../inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse('\n====== Bienven...')
#9 .../inc/parserutils.php(198): p_get_instructions('====== Bienvenu...')
#10 .../inc/parserutils.php(525): p_cached_instructions('/Users/dregad/w...', false, 'start')
#11 .../inc/parserutils.php(299): p_render_metadata('start', Array)
#12 .../inc/common.php(266): p_get_metadata('start')
#13 .../doku.php(97): pageinfo()
#14 {main}
```

### PR DESCRIPTION
**Pull request by dregad**
Fixes #143

### CODE REVIEW

**Comment by gturri** [comment]
oops, I looked at the bug report before looking at this pull request... .
I'll look at the rest of the PR now (and fix the subsequent conflicts)

**Comment by gturri** [comment]
That's great; thanks a lot for spotting and fixing those deprecated calls! :+1: 
One quick question before merging it: do have an idea how this may impact users with old versions of dokuwiki?
I mean: do you know what is going to be the minimal version of Dokuwiki required to run a version of nspages with those changes?

**Comment by dregad** [comment]
> That's great; thanks a lot for spotting and fixing those deprecated calls! 👍

You're welcome, consider this a token of my appreciation, to thank you for the plugin :wink:

> One quick question before merging it: do have an idea how this may impact users with old versions of dokuwiki?
> I mean: do you know what is going to be the minimal version of Dokuwiki required to run a version of nspages with those changes?

That's a good point, I did not really consider the compatibility with older DokuWiki versions as I tend to follow new releases quite closely and upgrade plugins as I go along, but I can see it could be useful to allow the plugin to work with older versions too.

To answer your question:
- resolve_pageid() was deprecated in Igor release (2022-07-31), and the PageResolver class replacement was introduced at the same time
- the utf8 functions replacements were introduced in Hogfather (2020-07-29)

If you need/want to maintain backwards-compatibility, I think it should be quite straightforward to achieve with a check on DokuWiki version, using getVersion() or maybe better $updateVersion global.

As for PHP versions support, this makes 7.1 the minimum, but effectively Igor requires 7.2 anyway. I *think* Hogfather was 5.6-7.4.

**Comment by dregad** [comment]
OK fine. 

If you want I can rebase the PR's branch on top of master after you're done, so it's in a clean state. Or submit a separate PR and close this one. Whatever you prefer.

**Comment by gturri** [comment]
Thanks for the proposition!
I'm done cherry-picking what could already be applied, so there are only the last 2 commits left to rebase.
I think it's cool if you update that one so we'll keep the comments and hence the context about why those have not been merged yet.

**Comment by dregad** [comment]
Rebased onto master as requested.

**Pull request merged**
