### PR TITLE
add custom title support for simple lists

### PR DESCRIPTION
**Pull request by StancuFlorin**
This is the first time I am using DokuWiki and I wanted to print all pages from a namespace. 

The nspages plugin is pretty good, but I wanted to list all pages in a simple list with my custom title. At this moment I only saw the "-h1" option that was not enough for me.

This PR adds support for a new parameter (-customTitle) and the value of this parameter should be the template of the title. Examples:
`<nspages :my-namespace -customTitle="{title} ({year}) by {user}">`
This will list the pages like this:
- Title Page 1 (2020) by florin
- Title Page 2 (2021) by florin

`<nspages :my-namespace -customTitle="{title} ({customMeta}) at {date.created}">`
This example will list the pages like this:
- Title Page 1 (something) at 1613325505
- Title Page 2 (something) at 1613325528

It can be use in conjustion with another plugins that adds support for custom metadatas (like [plugin:meta](https://www.dokuwiki.org/plugin:meta)). In my case "year" and "customMeta" are custom metadatas. If you don't have any custom metadatas you can easily access the default metadatas that are documented [here](https://www.dokuwiki.org/devel:metadata) (in my examples, "year" and "date.created" are default metadatas) .

### CODE REVIEW

**Comment by gturri** [comment]
Thanks for this patch!
It looks really nice. I just have one question: could this patch have an impact on security (in the sense that, if I understand correctly, any user could access all the metadata for any page he can read)? Could it for instance be used to retrieve the IP of the editors of a wiki?

**Comment by StancuFlorin** [comment]
Well, you are right. With the current version you can get the ip of the user who updated a page. This can be solved with an allow list of metadatas in admin config page.

**Comment by StancuFlorin** [comment]
I have updated the PR by adding support for metadata allow list.

**Comment by gturri** [comment]
That's a really nice way to tackle this issue (and I really like your code).
Thanks a lot for this pull request! 👍

**Pull request merged**
