### PR TITLE
add korean language sort

### PR DESCRIPTION
**Pull request by kabbala**
Hello

I added Korean Language sort support

please review this.

thanks

### CODE REVIEW

**Comment by gturri** [comment]
Thank you for this pull request.

Before I merge it I'd like to ask a few questions, to make sure I completely understand it. Could you explain to me:
- where do the bounds `44031`, `55204` come from on L83; what do they represent?
- why do we divide by 588 on L84?

Also, could you give me an example of page name (or page title) which would result in a buggy behavior without this patch (so I could add it in the automated non regression test suite)

thanks!

**Comment by kabbala** [comment]
Sure, it can be long story so i hesitated to include first comment.

the Korean character consists of three parts. consonant-vowel-consonant

it has some variations, but unicode block took 19 consonants - 21 vowels - 28 consonants

so there are 19 × 21 × 28 = 11,172 characters in unicode block.

its address starts with U+AC00(44032) and end with U+D7A3(55203).(some blank left)

ordinary Korean dictionary begins with the first 19 consonants, so 11,172 characters can be diveded by 588 characters.

**Comment by kabbala** [comment]
before

original rendering show all the titles were seperated. because Nspages regard they are all the different unicode characters. but Korean dictionary uses the first consonants.

after

**Comment by gturri** [comment]
Thanks for those explanations

**Pull request merged**
